### ISSUE TITLE
Atualizar campo "Situacao" da tabela HorarioSala 

### ISSUE THREAD

**Issue by igorb22** [fabricadesoftwareufs/AutomacaoSalas#37]
Atualizar o campo situacão da tabela HorarioSala (Reserva) adicionando os seguintes estados: 
Aprovada
Reprovada
Cancelada

**Comment by marcosdosea** [comment]
Quem aprova ou reprova? Não lembro disso.
Não seria: Disponível ou Reservada??

**Comment by igorb22** [comment]
Você falou que inicialmente ninguém iria fazer esse controle, só se por acaso surgisse a demanda no futuro.
Disponível e Reservada pode causar um pouco de confusão não ? uma sala sempre está disponível para ser reservada, e pode estar reservada em um determinado horário, mas isso não quer dizer que ela está ocupada para outras reservas em outros horários.
